name: Build

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APKs
        shell: bash {0}
        run: |
          exit_on_error() { echo "$1"; exit 1; }
          if ! ./gradlew assembleDebug; then
            exit_on_error "Build failed."
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Upload outputs dir
          path: |
            ./app/build/outputs/*
          retention-days: 7
