name: Build

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APKs
        run: ./gradlew assembleDebug

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Upload outputs dir
          path: |
            ./app/build/outputs/*
          retention-days: 7
